### ISSUE TITLE
IAM permissions and role

### ISSUE THREAD

**Issue by antoniomika** [schubergphilis/awsapilib#17]
Hello!

First off, thank you for creating this awesome tool!  I’ve been struggling to get the necessary permissions setup for an IAM user to use for the library. Currently, I have an administrator role and IAM user and the administrator user has permission to assume the role. The issue I’ve been having has been related to account level permissions. I enabled IAM access to billing on the account but it still seems that doesn’t work. Is there any documentation I’m missing to getting that setup or do you have any pointers on where I can go to set up user access properly?

Best,

**Comment by costastf** [comment]
Hi @antoniomika! I am sorry but it is not clear to me what does not work. Which module are you trying and it does not work? How does it not work? Do you get an exception on instantiation or an error message while trying to do something with it? Some code that you are trying would help me help you.

**Comment by antoniomika** [comment]
Hey @costastf,

Sorry about the delay, I had been traveling. I'm attempting to use the controltower lib. I'm going to add some of the code I'm using below and the specific policies I have defined. 

Here's the error I'm getting:

```json
{"__type":"AccessDeniedException","Message":"User does not have permissions to access account data for account xxxxxxxxx"}
```

Here's the example code below:

```python
import sys
import logging

import awsapilib
import click

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(),
    ]
)

LOGGER = logging.getLogger(__name__)

@click.command()
def main():
    controltower = awsapilib.ControlTower("arn:aws:iam::xxxxxxxxx:role/Administrator")

    controltower.deploy(
        logging_account_email=_render_email("logging"),
        security_account_email=_render_email("security"),
        regions=("us-east-1", "us-west-2"),
    )

def _render_email(after_plus: str = "", after_username: str = "") -> str:
    pass

if __name__ == "__main__":
    main()
```

The role has the `AdministratorAccess` permission set with the following policy:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

And trust relationship defined to allow the IAM user `arn:aws:iam::xxxxxxxx:user/Administrator` to assume the role. The user also had the same policy as above assigned to them. The environment has `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_DEFAULT_REGION` all defined.  I've also enabled IAM user access to billing information.

![image](https://user-images.githubusercontent.com/6239308/145261130-e674bab9-9af4-42f1-974a-48333f934d08.png)

Is there anything I'm missing? I went through the code path and can't discern what I'm missing, so any pointers would be appreciated!

Thanks again!

**Comment by costastf** [comment]
Have you given access to the role to the service catalog product of the account factory? Maybe that is what you are missing, although i think i am covering that with a custom exception. What is the actual stack trace of the exception you are getting? That might help me troubleshoot for you.

**Comment by costastf** [comment]
Sorry, i read your issue again and realized that you are trying to deploy control tower, so the service catalog permissions would have nothing to do with it. Please provide a detailed stack trace of your error so i can understand at which point the failure happens. Make sure to sanitize the output of any personal info or creds though!

**Comment by antoniomika** [comment]
Looks like there were some resources that had not been cleaned up after a previous control tower deployment. Sorry about the noise!

**Comment by costastf** [comment]
Happy to hear that your problem is resolved 😊
