### ISSUE TITLE
get_control_tower_authenticated_session method is broken

### ISSUE THREAD

**Issue by kiwi-33** [schubergphilis/awsapilib#37]
### awsapilib Version
2.3.1

### Expected Result
authenticated ControlTower session 

### Actual Result
This errors with:

```console
Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

I have managed to narrow it down to [this http request in authentication.py L454-459](https://github.com/schubergphilis/awsapilib/blob/main/awsapilib/authentication/authentication.py#L454-L459)

Printing the response content:

```console
...Your web browser must have JavaScript enabled...
```

**Comment by costastf** [comment]
It seems that they are in the process of rolling out the official API, the calls are going through to `https://prod.eu-west-1.blackbeard.aws.a2z.com/` for eu-west1. I fixed the authentication part but I all the calls go to a different end point now and the call structure is different. @s0enke has done quite some work on this a while back when they were rolling the apis again. Maybe he can chime in with a thought on how to move forward? I have pushed the current changes to https://github.com/schubergphilis/awsapilib/tree/control-tower-authentication just for reference.

**Comment by s0enke** [comment]
Yes, there is a WIP branch which uses the new API: https://github.com/schubergphilis/awsapilib/compare/main...superwerker:control_tower_native_api
Tracking the issue for superwerker here: https://github.com/superwerker/superwerker/issues/298 - I will focus on getting a hotfix out for superwerker first, though.

**Comment by s0enke** [comment]
superwerker is hotfixed by using the WIP branch https://github.com/schubergphilis/awsapilib/compare/main...superwerker:control_tower_native_api directly. This also ensures that at least the `deploy` function is working since it's covered by the superwerker integration tests.
