### ISSUE TITLE
Python 3.7 deprecation for aws lambda

### ISSUE THREAD

**Issue by aperov9** [schubergphilis/awsapilib#57]
People using the library to automate stuff on AWS via lambda will soon not be able to use the library anymore since AWS announced the depreciation phase 1 for python3.7 this year. See here: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy. 

Are there any plans to upgrade the library to a new python version?

**Comment by costastf** [comment]
The library has been working on 3.9 quite some time already. I forgot to update the marker in setup.py but that should not be an issue. I have a working branch trying to fix root authentication and once that is done I will release a new version with the marker update but this shouldn't be a blocker till then.
